### PR TITLE
Preserve state reference if unchanged and not in transaction

### LINKED ISSUE #22: New state object returned on unhandled action dispatch
I tend to include a test case like the following in most of my projects, to guard against unintentional state updates:

https://github.com/WordPress/gutenberg/blob/d0158e0/editor/test/state.js#L984-L994

With `redux-optimist`, the assertion fails because it appears to return a new object on every dispatch, regardless of whether the action was handled.

You can demonstrate this with the following snippet, an extension of the examples provided in the README:

```js
import reducer from './reducers';
import { createStore } from 'redux';

const store = createStore( reducer );

const originalState = store.getState();
store.dispatch( { type: 'UNHANDLED_ACTION' } );
if ( store.getState() !== originalState ) {
	throw new Error( 'Expected same reference' );
}
```

As a real-world example, here's a case I've worked on previously where state references are strictly compared to determine whether to persist to `localStorage`:

https://github.com/Automattic/wp-calypso/blob/3c5229d/client/state/initial-state.js#L119-L122

I believe the issue may be isolated to this line, where `innerState` is created as a new object by the spread result:

https://github.com/ForbesLindesay/redux-optimist/blob/19944bd/src/index.js#L138

### PR DESCRIPTION
**Pull request by aduth**
Fixes #22 

This pull request seeks to resolve an issue where `redux-optimist` returns a new state reference on every dispatch, regardless of whether the original reducer has in-fact returned a new value.

The approach is perhaps not quite as elegant as I'd hope, since it moves logic from what might otherwise be considered part of the `baseReducer` into the return function of the top-level `optimist`. After banging my head at several attempts trying to incorporate into `baseReducer` while also accommodating `commitReducer` and `revertReducer`, this is what I landed on.

The idea is that if we're not in the middle of a transaction and the original reducer produces a strictly equal value to the previous state, we shouldn't bother to separate state, which is not only potentially costly (in iterating over the spread assignment of `innerState` from `separateState`) but is the root cause for the new reference being returned (destructuring this way will guarantee `innerState` is always a new value).

I've included a test case which fails in master, and granted you access to edit my branch, in case you'd like to hack away at a refactor while achieving the same intent.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -109,8 +109,17 @@ function optimist(fn) {
           return revertReducer(state, action);
       }
     }
-    let separated = separateState(state);
-    return baseReducer(separated.optimist, separated.innerState, action);
+    if (!state || !state.optimist || state.optimist.length) {
+      let separated = separateState(state);
+      return baseReducer(separated.optimist, separated.innerState, action);      
+    }
+    let nextState = fn(state, action);
```
Comment (ForbesLindesay) [inline src/index.js]: We should still be separating out the state, I think.  otherwise the `fn` gets called with a different value depending on whether there is a transaction in progress. My suggestion would be to do:

```js
const separated = separateState(state);
const nextState = fn(separated.innerState, action);
if (nextState === separated.innerState) {
  return state;
}
validateState(nextState, action);
return nextState;
```

**Comment by aduth** [comment]
Thanks for the feedback @ForbesLindesay . I've made updates in 087cba9 to ensure that the original reducer is called with only the `innerState` value. It seems to be a fair bit more simplified now overall.

**Comment by aduth** [comment]
And for good measure, added an extra unit test in 1682380 to verify the expected behavior that the original reducer is not passed the state with `optimist`.

File: src/index.js [hunk 2]
```diff
@@ -109,8 +109,15 @@ function optimist(fn) {
           return revertReducer(state, action);
       }
     }
-    let separated = separateState(state);
-    return baseReducer(separated.optimist, separated.innerState, action);
+
+    let {optimist, innerState} = separateState(state);
+    if (state) {
+      let nextState = fn(innerState, action);
+      if (nextState === innerState && !optimist.length) {
```
Comment (ForbesLindesay) [inline src/index.js]: I think there are two new problems here:

1. If `optimist.length > 0` we should skip straight to baseReducer, not also run `fn` first.
2. It looks like `fn` is potentially getting called twice here (if it applies a change). The `fn` should only ever be called once per action.

**Comment by aduth** [comment]
>I think there are two new problems here:
>
>1. If `optimist.length > 0` we should skip straight to baseReducer, not also run `fn` first.
>2. It looks like `fn` is potentially getting called twice here (if it applies a change). The `fn` should only ever be called once per action.

Thanks for the continued feedback. This is addressed in 46b6329. I still get a sense there's some redundancy here with `baseReducer` (validating and returning the new merged state), but it's proven difficult to refactor `baseReducer` while also accommodating its use in the other reducer handlers.

**Comment by ForbesLindesay** [comment]
I think it's ok that some of the code is sort of duplicated, as long as we're not running potentially costly reducers unnecessarily.

**Comment by aduth** [comment]
Thanks @ForbesLindesay . While not entirely relevant to the changes here, considering [how the destructuring operates](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=MYewdgzgLgBNCGUCmMC8MDeBfA3AKDwHpCYA6cg0SWDGEABygEsBbJ6AGjPKbDCQBOAZSiIUWNHFHIcQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=) to separate state, an operation which may end up not yielding any changes, the pragmatist in me wonders if it's even worth trying to keep the `optimist` array in state itself, vs. a variable scoped to the return value of `optimist( reducer )`, avoiding the need for separating or combining the array from the `innerState`. Food for thought, in any case.

**Comment by ForbesLindesay** [comment]
The problem with doing that is that it wouldn't play nicely with other clever reducer additions like an "undo"/"redo" reducer. It's important that we keep all our state in redux's store.  Options that could be explored would be having the state always be `{optimist, value}`, but that requires all connect calls to separate out the `value` key, or passing optimist into the `fn` anyway, which would save us splitting it out, but does feel less "clean".
